CREATE DATABASE CERBERUS;

USE CERBERUS;

CREATE TABLE USUARIOS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(100) NOT NULL
	,EMAIL VARCHAR(100) NOT NULL UNIQUE
	,SENHA VARCHAR(150) NOT NULL 
	,TIPO_USUARIO VARCHAR(50) NOT NULL
)

CREATE TABLE PLACAS(
	ID INT IDENTITY PRIMARY KEY
	,CODIGO VARCHAR(255) NOT NULL
	,SITUACAO VARCHAR(255) NOT NULL
)

CREATE TABLE REINICIACOES(
	ID INT IDENTITY PRIMARY KEY 
	,DATA_OCORRIDA DATE NOT NULL
	,PLACA_ID INT FOREIGN KEY REFERENCES PLACAS(ID) NOT NULL
)

CREATE TABLE EMPRESAS(
	ID INT IDENTITY PRIMARY KEY 
	,NOME_FANTASIA VARCHAR(200) NOT NULL
	,TELEFONE VARCHAR(100) 
	,RESPONSAVEL VARCHAR(100) 
)

CREATE TABLE ENDERECOS(
	ID INT IDENTITY PRIMARY KEY 
	,LOGRADOURO VARCHAR(200) NOT NULL
	,CEP VARCHAR(100) NOT NULL
	,NUMERO INT
	,COMPLEMENTO VARCHAR(200)
	,OBSERVACAO VARCHAR(255)
	,BAIRRO VARCHAR(150) NOT NULL
	,CIDADE VARCHAR(150) NOT NULL
	,ESTADO VARCHAR(150) NOT NULL
	,EMPRESA_ID INT FOREIGN KEY REFERENCES EMPRESAS(ID) NOT NULL
)

CREATE TABLE PLACA_ENDERECO(
	ID INT IDENTITY PRIMARY KEY 
	,PLACA_ID INT FOREIGN KEY REFERENCES PLACAS(ID) NOT NULL
	,ENDERECO_ID INT FOREIGN KEY REFERENCES ENDERECOS(ID) NOT NULL
	,DATA_ENTRADA DATE NOT NULL
	,DATA_SAIDA DATE
	,TEMPO_DESLIGADO INT NOT NULL
	,TEMPO_ENTRE_TESTES INT NOT NULL
	,TEMPO_VOLTAR_TESTES INT NOT NULL
	,QUANTIDADE_PINGS INT NOT NULL
	,IP_ENDERECO VARCHAR(100) NOT NULL
)